CREATE TABLE `clients` (
	`id` integer PRIMARY KEY NOT NULL,
	`hostname` text,
	`scan_id` text,
	`thor_version` text,
	`admin_rights` text,
	`platform` text,
	`cpu_count` integer,
	`memory` integer,
	`ip` text
);
--> statement-breakpoint
CREATE TABLE `logs` (
	`accessed` text,
	`arch` text,
	`arguments` text,
	`author` text,
	`build_number` text,
	`cmd` text,
	`command` text,
	`company` text,
	`connection_count` integer,
	`context` text,
	`created` text,
	`desc` text,
	`duration` text,
	`end_time` text,
	`entries` integer,
	`entry` text,
	`event_id` integer,
	`event_level` integer,
	`event_time` text,
	`exists` text,
	`expires` text,
	`ext` text,
	`file` text,
	`firstbytes` text,
	`hostname` text NOT NULL,
	`id` integer PRIMARY KEY NOT NULL,
	`image_name` text,
	`image_path` text,
	`imphash` text,
	`installed_on` text,
	`internal_name` text,
	`ip` text,
	`launch_string` text,
	`legal_copyright` text,
	`level` text NOT NULL,
	`license` text,
	`listenPorts` text,
	`location` text,
	`log_accessed` text,
	`log_created` text,
	`log_modified` text,
	`log_version` integer NOT NULL,
	`matched` text,
	`match_string` text,
	`md5` text,
	`message` text NOT NULL,
	`modified` text,
	`module` text NOT NULL,
	`modules` text,
	`name` text,
	`original_name` text,
	`parent` text,
	`path` text,
	`perm` text,
	`permissions` text,
	`pid` integer,
	`port` integer,
	`ppid` integer,
	`proc` text,
	`process_name` text,
	`product` text,
	`reason` text,
	`reasons_count` integer,
	`ref` text,
	`reference` text,
	`rip` text,
	`rport` integer,
	`rule` text,
	`scan_id` text NOT NULL,
	`scanned_elements` integer,
	`scanner` text,
	`score` integer,
	`session` text,
	`sha1` text,
	`sha256` text,
	`sigclass` text,
	`sigtype` text,
	`size` text,
	`starts` text,
	`start_time` text,
	`subscore` text,
	`tags` text,
	`time` text NOT NULL,
	`user` text,
	`valid` text,
	`version` text,
	`client_id` integer,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE UNIQUE INDEX `hostname_idx` ON `clients` (`hostname`);--> statement-breakpoint
CREATE INDEX `level_idx` ON `logs` (`level`);--> statement-breakpoint
CREATE INDEX `module_idx` ON `logs` (`module`);